### ISSUE TITLE
Additional Decimal prior to .10 NOVA

### ISSUE THREAD

**Issue by WheelerCrypto** [KometFinance/app.komet.finance#39]
Staking reward prior to having an amount of 0.10 nova should display 0.09 NOVA

![photo_2020-12-22_12-40-12](https://user-images.githubusercontent.com/29384994/102892990-a7ebee80-4458-11eb-9459-2d6762bcfa12.jpg)

**Comment by KometHalley** [comment]
@WheelerCrypto can you see if you can reproduce it again? 
That should be resolved in the PR I've just merged and that's being deployed

**Comment by KometHalley** [comment]
I'll close that one since it's fixed.
