### ISSUE TITLE
Potential UI improvements

### ISSUE THREAD

**Issue by jonn4y** [KometFinance/app.komet.finance#42]
When hovering over the copy address button the title is default text:

<img src="https://i.imgur.com/NwT3eIq.png" height="100">

Please consider amending line
https://github.com/KometFinance/app.komet.finance/blob/e034278ef4e973c0c6ccad76e3401c611554210c/src/elm/View.elm#L508

To:
```
, title "Copy Address to Clipboard"
```

Also consider adding a slight border to the modal to make it more aesthetically pleasing

<img src="https://i.imgur.com/AjG0Y1p.png" height="200">

https://github.com/KometFinance/app.komet.finance/blob/e034278ef4e973c0c6ccad76e3401c611554210c/src/scss/_modal.scss#L171

```
 padding: $modal-inner-padding;
 border-radius: 10px;
```

Finally editing the below will add a pointer cursor to the copy address button as at present it shows the text cursor.

https://github.com/KometFinance/app.komet.finance/blob/e034278ef4e973c0c6ccad76e3401c611554210c/src/scss/_reboot.scss#L204

```
background-color: transparent; // Remove the gray background on active links in IE 10.
cursor: pointer;
```

Thank you.

**Comment by KometHalley** [comment]
@jonn4y should soon be deployed :) 

I went another way for most of the UI adjustment: in general, we want to go toward more tailwindcss and less bootstrap 😄 hence the small changes were done by adding classes
